package com.github.longdt.vertxorm.codegen;

import com.github.longdt.vertxorm.repository.Configuration;
import com.github.longdt.vertxorm.repository.CrudRepository;
import com.github.longdt.vertxorm.repository.SqlDialect;
import com.squareup.javapoet.*;
import io.vertx.sqlclient.Pool;

import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import java.io.IOException;

import static com.google.auto.common.GeneratedAnnotationSpecs.generatedAnnotationSpec;
import static com.squareup.javapoet.TypeSpec.classBuilder;
import static javax.lang.model.element.Modifier.PUBLIC;

public class RepositoryWriter {
    private final Filer filer;
    private final Elements elements;
    private final SourceVersion sourceVersion;
    private final Types types;

    RepositoryWriter(ProcessingEnvironment processingEnv) {
        this.filer = processingEnv.getFiler();
        this.elements = processingEnv.getElementUtils();
        this.sourceVersion = processingEnv.getSourceVersion();
        this.types = processingEnv.getTypeUtils();
    }

    void writeRepository(RepositoryDescriptor descriptor)
            throws IOException {
        String factoryName = descriptor.name().className();
        TypeSpec.Builder factory =
                classBuilder(factoryName)
                        .addOriginatingElement(descriptor.repositoryDeclaration().targetType());
        generatedAnnotationSpec(
                elements,
                sourceVersion,
                CodeGenProcessor.class,
                "Do not edit this file")
                .ifPresent(factory::addAnnotation);
        factory.addSuperinterface(descriptor.repositoryDeclaration().targetType().asType());
        factory.addModifiers(PUBLIC);
        addSuperclass(factory, descriptor);
        addConstructor(factory, descriptor);

        JavaFile.builder(descriptor.name().packageName(), factory.build())
                .skipJavaLangImports(true)
                .build()
                .writeTo(filer);
    }

    private void addConstructor(TypeSpec.Builder factory, RepositoryDescriptor descriptor) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder();
        constructor.addModifiers(PUBLIC);
        constructor.addParameter(TypeName.get(Pool.class), "pool");
        var entityDeclaration = descriptor.entityDeclaration();
        var entityElement = entityDeclaration.targetType();
        var idField = entityDeclaration.idField();
        constructor.addCode("var conf = new $T<$T, $T>()\n",
                Configuration.class,
                idField.javaType(),
                entityElement);
        constructor.addCode("\t\t.setTableName($T.$L)\n", ClassName.bestGuess(entityElement.toString() + Constant.TABLE), Constant.TABLE_NAME);
        constructor.addCode("\t\t.setColumnNames($T.$L)\n", ClassName.bestGuess(entityElement.toString() + Constant.TABLE), Constant.COLUMN_NAMES);
        constructor.addCode("\t\t.setIdAccessor($T.$L)\n", ClassName.bestGuess(entityElement.toString() + Constant.ID_ACCESSOR), Constant.INSTANCE);
        constructor.addCode("\t\t.setParametersMapper($T.$L)\n", ClassName.bestGuess(entityElement.toString() + Constant.PARAMETERS_MAPPER), Constant.INSTANCE);
        constructor.addCode("\t\t.setRowMapper($T.$L);\n", ClassName.bestGuess(entityElement.toString() + Constant.ROW_MAPPER), Constant.INSTANCE);
        constructor.addStatement("init(pool, conf)");
        factory.addMethod(constructor.build());
    }



    private boolean hasExtend(TypeMirror extendingType) {
        return !types.asElement(extendingType).toString().equals(CrudRepository.class.getTypeName());
    }

    private void addSuperclass(TypeSpec.Builder factory, RepositoryDescriptor descriptor) {
        if (hasExtend(descriptor.extendingType())) {
            factory.superclass(descriptor.extendingType());
            return;
        }
        var supperClass = descriptor.repositoryDeclaration().dialect() == SqlDialect.POSTGRES ?
                com.github.longdt.vertxorm.repository.postgresql.AbstractCrudRepository.class
                : com.github.longdt.vertxorm.repository.mysql.AbstractCrudRepository.class;
        factory.superclass(ParameterizedTypeName.get(
                ClassName.get(supperClass),
                ClassName.get(descriptor.entityDeclaration().idField().javaType()),
                ClassName.get(descriptor.entityDeclaration().targetType())
        ));
    }

}
